name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: docker/login-action@v1.6.0
      name: login
      with:
        registry: megamanics.jfrog.io
        username: ${JUSER}
        password: ${PASSWORD}
    
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
      docker build . --file Dockerfile --tag megamanics.jfrog.io/docker/my-docker-image:latest
      docker push megamanics.jfrog.io/docker/my-docker-image:latest
